packages:
  adamctl: 0.0.9
  crush: 0.6.2
  delta: 0.18.2
  diffsitter: 0.9.0
  direnv: 2.37.1
  fzf: 0.65.1
  grab: 0.0.68
  hyperfine: 1.19.0
  lefthook: 1.12.3
  rg: 14.1.1
  scc: 3.5.0
  starship: 1.23.0
  yazi: 25.5.31
