packages:
  adamctl: 0.0.9
  crush: 0.19.4
  delta: 0.18.2
  diffsitter: 0.9.0
  direnv: 2.37.1
  fzf: 0.67.0
  grab: 0.0.68
  hyperfine: 1.20.0
  lefthook: 2.0.4
  rg: 15.1.0
  scc: 3.6.0
  starship: 1.24.1
  yazi: 25.5.31
